// PROBLEM --------------------------------------------------------------------------------------------
// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

// Example 2:
// Input: s = "", t = "y"
// Output: "y"

// IDE ------------------------------------------------------------------------------------------------
// 1. Kita lakukan iterasi untuk setiap char dalam s
// 2. Periksa apakah ada char yang sama di dalam t
// 3. Jika ada hapus dari string menggunakan replace()
// 4. Jika ada char yang berbeda maka char tersebut tidak dihapus dari string

// CODE -----------------------------------------------------------------------------------------------

function findTheDifference(s, t) {
  for (const char of s) {
    // Jika char terdapat pada keduanya maka replace dengan string kosong
    t = t.replace(char, "");
  }
  // return sisa char di dalam t
  return t;
}

// Contoh penggunaan
const string = findTheDifference("abcd", "abcde");
console.log(string);
